os: osx
osx_image: xcode11.6
language: swift
xcode_workspace: Goalie/Goalie.xcworkspace
xcode_scheme: Travis
xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone 11
podfile: Goalie/
before_install:
  - gem install cocoapods --pre
  - pod install --repo-update
