os: osx
osx_image: xcode11.6
language: swift
xcode_workspace: Goalie/Goalie.xcworkspace
xcode_scheme: Travis
xcode_destination: platform=iOS Simulator,OS=13.6,name=iPhone 11
before_install:
    - gem install cocoapods --pre
install:
    - cd Goalie
    - pod install --repo-update
    - cd Goalie
    - echo "<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">
<plist version=\"1.0\">
<dict>
    <key>CLIENT_ID</key>
    <string>219163178912-qfvel44s746dq4soiq8a6rt1jrig82jb.apps.googleusercontent.com</string>
    <key>REVERSED_CLIENT_ID</key>
    <string>com.googleusercontent.apps.219163178912-qfvel44s746dq4soiq8a6rt1jrig82jb</string>
    <key>API_KEY</key>
    <string>" + $firebaseKey + "</string>
    <key>GCM_SENDER_ID</key>
    <string>219163178912</string>
    <key>PLIST_VERSION</key>
    <string>1</string>
    <key>BUNDLE_ID</key>
    <string>com.gmail.adams.s.r.jack.Goalie</string>
    <key>PROJECT_ID</key>
    <string>goalie-91e5b</string>
    <key>STORAGE_BUCKET</key>
    <string>goalie-91e5b.appspot.com</string>
    <key>IS_ADS_ENABLED</key>
    <false></false>
    <key>IS_ANALYTICS_ENABLED</key>
    <false></false>
    <key>IS_APPINVITE_ENABLED</key>
    <true></true>
    <key>IS_GCM_ENABLED</key>
    <true></true>
    <key>IS_SIGNIN_ENABLED</key>
    <true></true>
    <key>GOOGLE_APP_ID</key>
    <string>1:219163178912:ios:67d64ce101f9f974cc16c5</string>
    <key>DATABASE_URL</key>
    <string>https://goalie-91e5b.firebaseio.com</string>
</dict>
</plist>" >> GoogleService-Info.plist
    - cd ../..
