# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Goalie' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'Firebase/Analytics'
  pod 'FirebaseUI/Auth'
  pod 'FirebaseUI/Email'
  pod 'FirebaseUI/Google'
  pod 'FirebaseUI/Facebook'
  pod 'FirebaseUI/Phone'
  pod 'FirebaseUI/OAuth'
  pod 'Eureka'
  # Pods for Goalie

  target 'GoalieTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GoalieUITests' do
    # Pods for testing
  end

end
